SELECT
    COALESCE(Data_Liberacao_dt, Data_Processamento_dt, Data_Coleta_dt, Data_Solicitacao_dt) AS data,
    COALESCE(Data_Liberacao_dt, Data_Processamento_dt, Data_Coleta_dt, Data_Solicitacao_dt) AS data_referencia,
    IBGE_Municipio_Residencia_Paciente AS cod_ibge,
    Municipio_Residencia_Paciente AS municipio,
    Regional_Cadastro AS regional_saude,
    Requisicao AS requisicao,
    Agravo_Requisicao AS agravo,
    Agravo_Gal AS agravo_gal,
    CID_Agravo_Gal AS cid_agravo,
    Exame AS exame,
    Metodologia AS metodologia,
    Material_Biologico AS material_biologico,
    Amostra AS amostra,
    Status_Exame AS status_exame,
    Campo_Resultado_1 AS resultado_1,
    Campo_Resultado_2 AS resultado_2,
    Campo_Resultado_3 AS resultado_3,
    Campo_Resultado_4 AS resultado_4,
    Campo_Resultado_5 AS resultado_5,
    Campo_Resultado_6 AS resultado_6,
    Observacao_Resultado AS observacao_resultado,
    Unidade_Solicitante AS unidade_solicitante,
    CNES_Unidade_Solicitante AS cnes_unidade_solicitante,
    Data_Solicitacao_dt AS data_solicitacao,
    Data_Coleta_dt AS data_coleta,
    Data_Recebimento_dt AS data_recebimento,
    Data_Liberacao_dt AS data_liberacao,
    DT_Atualizacao AS data_atualizacao
FROM dbo.VW_GAL
WHERE COALESCE(Data_Liberacao_dt, Data_Processamento_dt, Data_Coleta_dt, Data_Solicitacao_dt) >= DATEADD(day, -180, GETDATE());
