# -*- coding: utf-8 -*-
"""Regrava config/plano_el_nino_participantes.yaml com a lista operacional da Sala (2026-08-29)."""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "config" / "plano_el_nino_participantes.yaml"

# Lista CIEVS (29/08/2026) — nomes/e-mails conforme mensagem operacional.
PARTICIPANTES = [
    {
        "nome": "EMMANUEL SANTANA ARDAIA",
        "email": "saf@ses.mt.gov.br",
        "superintendencia": "Superintendência de Assistência Farmacêutica",
        "coordenadoria": "",
        "gerencia": "",
        "area_texto": "Assistência Farmacêutica",
        "sigla": "SAF",
        "area_id": "assistencia_farmaceutica",
        "telefone": "(65) 98462-7045",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "LAURA ALVES DA SILVA",
        "email": "farmaciabasica@ses.mt.gov.br",
        "superintendencia": "Superintendência de Assistência Farmacêutica",
        "coordenadoria": "Coordenadoria de Assistência Farmacêutica Primária e Estratégica",
        "gerencia": "",
        "area_texto": "Assistência Farmacêutica",
        "sigla": "SAF",
        "area_id": "assistencia_farmaceutica",
        "telefone": "(65) 98432-2593",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "MARLENE DA COSTA BARROS",
        "email": "covam@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância em Saúde Ambiental",
        "gerencia": "",
        "area_texto": "Vigilância Ambiental",
        "sigla": "COVAM",
        "area_id": "vigilancia_ambiental",
        "telefone": "(65) 98464-5551",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "ROBERTA SOUZA SILVA ORRIGO",
        "email": "robertaorrigo@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância em Saúde Ambiental",
        "gerencia": "Gerência de Vigilância em Saúde Ambiental",
        "area_texto": "Vigiágua",
        "sigla": "VIGIAGUA",
        "area_id": "vigiagua",
        "telefone": "(65) 98404-4831",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "NORANEY NASCIMENTO ALMEIDA",
        "email": "noraneyalmeida@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância em Saúde Ambiental",
        "gerencia": "Gerência de Vigilância em Saúde Ambiental",
        "area_texto": "Vigiar",
        "sigla": "VIGIAR",
        "area_id": "vigiar",
        "telefone": "(65) 98113-2038",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "SUZI MONTE DA CRUZ",
        "email": "suzicruz@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância em Saúde Ambiental",
        "gerencia": "Gerência de Vigilância em Saúde Ambiental",
        "area_texto": "Vigidesastre",
        "sigla": "VIGIDESASTRE",
        "area_id": "cievs",
        "telefone": "(65) 98140-5200",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "VERUSKA NOGUEIRA DE BRITO",
        "email": "veruskanbrito@gmail.com",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância em Saúde Ambiental",
        "gerencia": "Gerência de Controle de Vetores e Zoonoses",
        "area_texto": "Arboviroses",
        "sigla": "CVE",
        "area_id": "vigilancia_ambiental",
        "telefone": "(65) 99222-9868",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "MARCIA ALVES BRITO",
        "email": "marciabrito@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância em Saúde Ambiental",
        "gerencia": "Gerência de Controle de Vetores e Zoonoses",
        "area_texto": "Animais peçonhentos",
        "sigla": "CVE",
        "area_id": "vigilancia_ambiental",
        "telefone": "(65) 99696-8828",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "JANAÍNA PAULI",
        "email": "janainapauli@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância Epidemiológica",
        "gerencia": "",
        "area_texto": "Vigilância Epidemiológica",
        "sigla": "CVE",
        "area_id": "vigilancia_ambiental",
        "telefone": "",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "CECÍLIA CINTRA DOS REIS",
        "email": "dengue@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância Epidemiológica",
        "gerencia": "Gerência em Vigilância em Doenças e Agravos Endêmicos",
        "area_texto": "Arboviroses",
        "sigla": "CVE",
        "area_id": "vigilancia_ambiental",
        "telefone": "",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "MICHEL BELMONTE",
        "email": "michelbelmonte@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância Epidemiológica",
        "gerencia": "",
        "area_texto": "COVID/Influenza e vírus respiratórios",
        "sigla": "CVE",
        "area_id": "vigilancia_ambiental",
        "telefone": "",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "LÍDIA FOLLETO",
        "email": "nevh@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância Epidemiológica",
        "gerencia": "",
        "area_texto": "RENAVEH",
        "sigla": "NEVH",
        "area_id": "vigilancia_ambiental",
        "telefone": "",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "JOÃO PEDRO ROCHA NOGUEIRA",
        "email": "dengue@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância Epidemiológica",
        "gerencia": "",
        "area_texto": "Arboviroses",
        "sigla": "CVE",
        "area_id": "vigilancia_ambiental",
        "telefone": "",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "FABIANA COELHO DA SILVA ALVES",
        "email": "dtha@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância Epidemiológica",
        "gerencia": "",
        "area_texto": "DTHA",
        "sigla": "CVE",
        "area_id": "vigilancia_ambiental",
        "telefone": "",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "SÔNIA CRISTINA FIGUEIREDO OLIVEIRA",
        "email": "covsan@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância Sanitária",
        "gerencia": "",
        "area_texto": "Vigilância Sanitária",
        "sigla": "COVSAN",
        "area_id": "vigilancia_sanitaria",
        "telefone": "(65) 98464-5561",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "SILVANA CRISTINA SILVA BATISTA",
        "email": "gimvisa@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância Sanitária",
        "gerencia": "Gerência de Fiscalização, Inspeção e Monitoramento em Vigilância Sanitária",
        "area_texto": "Vigilância Sanitária",
        "sigla": "GIMVISA",
        "area_id": "vigilancia_sanitaria",
        "telefone": "(65) 98464-2437",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "LETICIA DE CAMPOS FERREIRA",
        "email": "gimvisa@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância Sanitária",
        "gerencia": "Gerência de Fiscalização, Inspeção e Monitoramento em Vigilância Sanitária",
        "area_texto": "Vigilância Sanitária",
        "sigla": "GIMVISA",
        "area_id": "vigilancia_sanitaria",
        "telefone": "(65) 98464-2437",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "TACIANA KATUCIA BESERRA DE OLIVEIRA FERREIRA",
        "email": "tacianaferreira@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria do Programa Estadual de Imunização",
        "gerencia": "",
        "area_texto": "Imunização",
        "sigla": "CPEI",
        "area_id": "imunizacao",
        "telefone": "(66) 99988-5398",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "GUILHERME VIEIRA BOTELHO DE ALMEIDA",
        "email": "gimvisa@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância Sanitária",
        "gerencia": "Gerência de Fiscalização, Inspeção e Monitoramento em Vigilância Sanitária",
        "area_texto": "Vigilância Sanitária",
        "sigla": "GIMVISA",
        "area_id": "vigilancia_sanitaria",
        "telefone": "(65) 98464-2437",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "SIRIANA MARIA DA SILVA",
        "email": "sgr@ses.mt.gov.br",
        "superintendencia": "Superintendência de Gestão Regional",
        "coordenadoria": "",
        "gerencia": "",
        "area_texto": "Gestão Regional",
        "sigla": "SGR",
        "area_id": "multi_area",
        "telefone": "(65) 99951-0569",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "consulta",
    },
    {
        "nome": "CLAUDIA MOLINA DE FRANÇA",
        "email": "cotgr@ses.mt.gov.br",
        "superintendencia": "Superintendência de Gestão Regional",
        "coordenadoria": "Coordenadoria de Gestão Regional",
        "gerencia": "",
        "area_texto": "Gestão Regional",
        "sigla": "SGR",
        "area_id": "multi_area",
        "telefone": "(65) 98110-3295",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "consulta",
    },
    {
        "nome": "Lauren Cristiane Leite Ocampos",
        "email": "costra@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância em Saúde do Trabalhador",
        "gerencia": "",
        "area_texto": "Saúde do Trabalhador",
        "sigla": "COVST",
        "area_id": "saude_trabalhador",
        "telefone": "(65) 99249-3790",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "Flávia Ribeiro Cardoso Fernandes Tortorelli",
        "email": "flaviatortorelli@ses.mt.gov.br",
        "superintendencia": "Superintendência de Vigilância em Saúde",
        "coordenadoria": "Coordenadoria de Vigilância em Saúde do Trabalhador",
        "gerencia": "",
        "area_texto": "Saúde do Trabalhador",
        "sigla": "COVST",
        "area_id": "saude_trabalhador",
        "telefone": "(65) 98145-2468",
        "papel": "grupo_tecnico",
        "perfil_sugerido": "tecnico_area",
    },
    {
        "nome": "Menandes Alves de Souza Neto",
        "email": "menandesneto@ses.mt.gov.br",
        "superintendencia": "Gabinete da Secretaria Adjunta de Atenção e Vigilância em Saúde",
        "coordenadoria": "Centro de Informações Estratégicas de Vigilância em Saúde",
        "gerencia": "",
        "area_texto": "CIEVS",
        "sigla": "CIEVS",
        "area_id": "cievs",
        "telefone": "",
        "papel": "secretaria_executiva",
        "perfil_sugerido": "secretaria_executiva_cievs",
    },
    {
        "nome": "Tatiana Helena Belmonte",
        "email": "tatianabelmonte@ses.mt.gov.br",
        "superintendencia": "Gabinete da Secretaria Adjunta de Atenção e Vigilância em Saúde",
        "coordenadoria": "Centro de Informações Estratégicas de Vigilância em Saúde",
        "gerencia": "",
        "area_texto": "CIEVS",
        "sigla": "CIEVS",
        "area_id": "cievs",
        "telefone": "(65) 98111-2625",
        "papel": "secretaria_executiva",
        "perfil_sugerido": "secretaria_executiva_cievs",
    },
]

REGIONAIS_AGREGADO = [
    {
        "nome": "Rede CIEVS MT e Escritórios Regionais de Saúde",
        "email": "rede-cievs-mt-e-ers@ses.mt.gov.br",
        "sigla": "Rede CIEVS / ERS",
        "papel": "escritorio_regional",
        "status_indicacao": "Lista agregada SES — e-mails individuais por escritório ainda pendentes",
        "fonte": "CONTATOS_AREAS_TECNICAS_SES_MT_2026.xlsx",
    }
]

# 16 regionais de saúde MT (nomes operacionais ARARAS) — e-mail individual a preencher.
PENDENCIAS_REGIONAIS = [
    "Alta Floresta",
    "Baixada Cuiabana",
    "Barra do Garças",
    "Cáceres",
    "Colíder",
    "Diamantino",
    "Juara",
    "Juína",
    "Peixoto de Azevedo",
    "Pontes e Lacerda",
    "Porto Alegre do Norte",
    "Rondonópolis",
    "Sinop",
    "São Félix do Araguaia",
    "Tangará da Serra",
    "Água Boa",
]

COSEMS = [
    {
        "nome": "COSEMS-MT — Conselho de Secretarias Municipais de Saúde de Mato Grosso",
        "email": "cosems@cosemsmt.org",
        "sigla": "COSEMS/MT",
        "papel": "convidado_externo",
        "telefone": "(65) 3644-2406 / (65) 3644-3914",
        "status_indicacao": "Contato público (site COSEMS-MT)",
        "fonte": "https://cosemsmt.org.br/quem-somos/",
    }
]


def main() -> None:
    old = yaml.safe_load(PATH.read_text(encoding="utf-8")) or {}
    rows = []
    for raw in PARTICIPANTES:
        row = dict(raw)
        row["status_indicacao"] = "Lista operacional Sala — 2026-08-29"
        row["fonte"] = "CIEVS_lista_sala_20260829"
        rows.append(row)

    data = {
        "fonte": "Lista operacional CIEVS 2026-08-29 + Rede ERS + COSEMS-MT",
        "ato": "Portaria nº 0590/2026/GBSES",
        "atualizado_em": "2026-08-29",
        "regra": (
            "Sala só abre para ses/admin. Distribuição do boletim El Niño usa "
            "participantes + rede ERS + COSEMS. E-mails individuais dos 16 escritórios "
            "regionais ainda pendentes de cadastro."
        ),
        "participantes": rows,
        "escritorios_regionais": REGIONAIS_AGREGADO,
        "pendencias_regionais_email": PENDENCIAS_REGIONAIS,
        "cosems": COSEMS,
        "sem_email": ["KAROL STÉFFANI GUIMARÃES"],
        "municipios_estrategicos": old.get("municipios_estrategicos") or [],
    }
    PATH.write_text(
        yaml.safe_dump(data, allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8",
    )
    emails = {r["email"].lower() for r in rows if r.get("email")}
    print(f"Gravado {PATH}")
    print(f"Participantes: {len(rows)} · e-mails únicos SES/convidados: {len(emails)}")
    print(f"Rede ERS: {len(REGIONAIS_AGREGADO)} · COSEMS: {len(COSEMS)}")
    print(f"Pendências ERS individuais: {len(PENDENCIAS_REGIONAIS)}")
    print(f"Municípios estratégicos preservados: {len(data['municipios_estrategicos'])}")


if __name__ == "__main__":
    main()
