[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[ui]
hideTopBar = false

[server]
headless = true
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0F6E56"
backgroundColor = "#F3F6F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A2E28"
font = "sans serif"
